---
- name: Check NTP service had installed ?
  command: systemctl status ntpd
  ignore_errors: yes
  register: ntp_service

- name: Install NTP service if not existed
  yum: name=ntp state=present
  when: "ntp_service.rc != 0" 

- name: check if chronyd services is exists
  command: systemctl status chronyd
  ignore_errors: yes
  register: chronyd_status

- name: disabled chronyd
  service: name=chronyd enabled=no
  when: "chronyd_status.rc == 0"

- name: Copy ntp.conf.j2
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  
- name: Add NTP server
  blockinfile:
    dest: /etc/ntp.conf
    marker: "# {mark} {{ item }}"
    insertafter: "#Insert NTP Server"
    content: |
       server {{ item }}
  with_items: "{{ntp_server.split(';')}}"

- name: Start ntp service
  systemd: state=started name=ntpd

- name: Be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes


